version: '3.8'

services:
  # MongoDB service (nếu muốn chạy cùng Docker)
  mongo-keygen:
    image: mongo:7
    container_name: mongo-keygen
    volumes:
      - ./mongo-keyfile:/keyfile
    entrypoint: >
      bash -c "
      if [ ! -f /keyfile/keyfile ]; then
        echo 'Generating mongo keyfile...';
        openssl rand -base64 756 > /keyfile/keyfile;
        chmod 400 /keyfile/keyfile;
      fi
      "
    restart: "no"

  mongodb:
    image: mongo:7
    container_name: mongodb
    depends_on:
      - mongo-keygen
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo_data:/data/db
      - ./mongo-keyfile/keyfile:/etc/mongo-keyfile:ro
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all", "--keyFile", "/etc/mongo-keyfile"]

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=changeme   # mật khẩu quản trị
    ports:
      - "9200:9200"    # HTTP REST API
      - "9300:9300"    # giao tiếp giữa các node
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - esnet
      
volumes:
  mongo_data:
  es_data:

networks:
  esnet:
